// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFn_9pHJiuG18GMKm-_R465KR15BnB-E',
    appId: '1:1034782294627:web:5b83b47fccdfa1d1f66e56',
    messagingSenderId: '1034782294627',
    projectId: 'dukabook-ff425',
    authDomain: 'dukabook-ff425.firebaseapp.com',
    storageBucket: 'dukabook-ff425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkfLWj2un5tzlDPO-oUpEancgJRepWzVI',
    appId: '1:1034782294627:android:485a1ba42e8e155bf66e56',
    messagingSenderId: '1034782294627',
    projectId: 'dukabook-ff425',
    storageBucket: 'dukabook-ff425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7gnF8-dcIlsNL7vmFdfmxzIcT1Ffq07o',
    appId: '1:1034782294627:ios:b5ef58b74138ed7cf66e56',
    messagingSenderId: '1034782294627',
    projectId: 'dukabook-ff425',
    storageBucket: 'dukabook-ff425.firebasestorage.app',
    iosBundleId: 'com.example.dukaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7gnF8-dcIlsNL7vmFdfmxzIcT1Ffq07o',
    appId: '1:1034782294627:ios:b5ef58b74138ed7cf66e56',
    messagingSenderId: '1034782294627',
    projectId: 'dukabook-ff425',
    storageBucket: 'dukabook-ff425.firebasestorage.app',
    iosBundleId: 'com.example.dukaBook',
  );
}
